<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.2.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'SILVER Package Customer Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'silver-package.html',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'customers@mindsts.com',
		'to' => 'customers@mindsts.com'
	),
	'fields' => array(
		'custom_U1594' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'الإسم',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'الإسم\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'الإيميل',
			'required' => false,
			'errors' => array(
				'format' => 'Field \'الإيميل\' has an invalid email.'
			)
		),
		'custom_U1637' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'رقم الهاتف الجوال',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'رقم الهاتف الجوال\' is required.'
			)
		),
		'custom_U1763' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'نوع المركبة',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'نوع المركبة\' is required.'
			)
		),
		'custom_U1779' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'رقم لوحة المركبة',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'رقم لوحة المركبة\' is required.'
			)
		),
		'custom_U1654' => array(
			'order' => 4,
			'type' => 'radiogroup',
			'label' => 'فئة المركبة',
			'required' => true,
			'optionItems' => array(
				'المميز',
				'تكسي أصفر',
				'مركبة خاصة'
			),
			'errors' => array(
				'required' => 'Field \'فئة المركبة\' is required.',
				'format' => 'Field \'فئة المركبة\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
